on:
   push:
      branches:
         - main

permissions:
   contents: write
   pull-requests: write

name: Release

jobs:
   release-please:
      runs-on: ubuntu-latest
      steps:
         - uses: google-github-actions/release-please-action@v4
           with:
              # this is a built-in strategy in release-please, see "Action Inputs"
              # for more options
              release-type: node
